"""rename address

Revision ID: 334a8341b62b
Revises: fd6ea9835cf5
Create Date: 2024-08-06 22:03:32.708955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334a8341b62b'
down_revision = 'fd6ea9835cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
